In [2]:
import numpy as np

In [3]:
a = np.array(range(10))

In [4]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.sum(a)

45

In [6]:
a >10

array([False, False, False, False, False, False, False, False, False,
       False])

In [7]:
a = np.random.rand(100)

In [13]:
a = np.full((7,7),700)

In [14]:
a

array([[700, 700, 700, 700, 700, 700, 700],
       [700, 700, 700, 700, 700, 700, 700],
       [700, 700, 700, 700, 700, 700, 700],
       [700, 700, 700, 700, 700, 700, 700],
       [700, 700, 700, 700, 700, 700, 700],
       [700, 700, 700, 700, 700, 700, 700],
       [700, 700, 700, 700, 700, 700, 700]])

In [15]:
a = np.array((9,9))

In [16]:
a

array([9, 9])

In [18]:
a = np.zeros((99,99),dtype=float)

In [19]:
a

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [26]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
a = np.zeros((7,3))

In [28]:
a.shape

(7, 3)

# 变形

In [29]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
a.reshape(2,2)

ValueError: cannot reshape array of size 21 into shape (2,2)

In [32]:
a = np.full((1,24),7.7777,dtype=float)

In [33]:
a

array([[7.7777, 7.7777, 7.7777, 7.7777, 7.7777, 7.7777, 7.7777, 7.7777,
        7.7777, 7.7777, 7.7777, 7.7777, 7.7777, 7.7777, 7.7777, 7.7777,
        7.7777, 7.7777, 7.7777, 7.7777, 7.7777, 7.7777, 7.7777, 7.7777]])

In [34]:
print(a.reshape(2,12))

[[7.7777 7.7777 7.7777 7.7777 7.7777 7.7777 7.7777 7.7777 7.7777 7.7777
  7.7777 7.7777]
 [7.7777 7.7777 7.7777 7.7777 7.7777 7.7777 7.7777 7.7777 7.7777 7.7777
  7.7777 7.7777]]


In [35]:
print(a.reshape(3,8))

[[7.7777 7.7777 7.7777 7.7777 7.7777 7.7777 7.7777 7.7777]
 [7.7777 7.7777 7.7777 7.7777 7.7777 7.7777 7.7777 7.7777]
 [7.7777 7.7777 7.7777 7.7777 7.7777 7.7777 7.7777 7.7777]]


In [36]:
print(a.reshape(4,6))

[[7.7777 7.7777 7.7777 7.7777 7.7777 7.7777]
 [7.7777 7.7777 7.7777 7.7777 7.7777 7.7777]
 [7.7777 7.7777 7.7777 7.7777 7.7777 7.7777]
 [7.7777 7.7777 7.7777 7.7777 7.7777 7.7777]]


# 排序

In [44]:
a = np.random.random(100000)

In [45]:
%timeit sum(a)

7.28 ms ± 176 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [46]:
%timeit np.sum(a)

30.4 µs ± 1.78 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [49]:
%timeit np.sort(a)

7 ms ± 183 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [51]:
%timeit a.sort()

1.8 ms ± 54 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [52]:
a = [
    [4,23,53],
    [5,6462,2],
    [334,5635,11]
]

In [53]:
print(np.sort(a))

[[   4   23   53]
 [   2    5 6462]
 [  11  334 5635]]


In [54]:
print(a.sort())

None


In [55]:
a.sort()

In [56]:
a

[[4, 23, 53], [5, 6462, 2], [334, 5635, 11]]

# 拼接

#### 按行拼接

In [59]:
np.concatenate([a,a,a],axis=0)

array([[   4,   23,   53],
       [   5, 6462,    2],
       [ 334, 5635,   11],
       [   4,   23,   53],
       [   5, 6462,    2],
       [ 334, 5635,   11],
       [   4,   23,   53],
       [   5, 6462,    2],
       [ 334, 5635,   11]])

#### 按列拼接

In [60]:
np.concatenate([a,a,a],axis=1)

array([[   4,   23,   53,    4,   23,   53,    4,   23,   53],
       [   5, 6462,    2,    5, 6462,    2,    5, 6462,    2],
       [ 334, 5635,   11,  334, 5635,   11,  334, 5635,   11]])

# Rand

In [61]:
np.random.randint(1,10,(5,5))

array([[8, 3, 6, 5, 6],
       [8, 1, 1, 2, 3],
       [2, 7, 3, 7, 3],
       [3, 4, 8, 4, 2],
       [8, 7, 1, 2, 7]])

In [63]:
np.random.random((5,5))

array([[0.2197349 , 0.09161687, 0.46333996, 0.48809174, 0.70013117],
       [0.62157434, 0.67834922, 0.11639141, 0.32840727, 0.06650603],
       [0.57936892, 0.62071268, 0.85562714, 0.57337435, 0.23530696],
       [0.80956798, 0.20675604, 0.96627992, 0.67853127, 0.16039024],
       [0.58272033, 0.41891003, 0.1627387 , 0.26977998, 0.36304588]])

#### 单位矩阵

In [64]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [66]:
np.linspace(0,7,77) #产生从0到7之间的步长相等的77个数组元素

array([0.        , 0.09210526, 0.18421053, 0.27631579, 0.36842105,
       0.46052632, 0.55263158, 0.64473684, 0.73684211, 0.82894737,
       0.92105263, 1.01315789, 1.10526316, 1.19736842, 1.28947368,
       1.38157895, 1.47368421, 1.56578947, 1.65789474, 1.75      ,
       1.84210526, 1.93421053, 2.02631579, 2.11842105, 2.21052632,
       2.30263158, 2.39473684, 2.48684211, 2.57894737, 2.67105263,
       2.76315789, 2.85526316, 2.94736842, 3.03947368, 3.13157895,
       3.22368421, 3.31578947, 3.40789474, 3.5       , 3.59210526,
       3.68421053, 3.77631579, 3.86842105, 3.96052632, 4.05263158,
       4.14473684, 4.23684211, 4.32894737, 4.42105263, 4.51315789,
       4.60526316, 4.69736842, 4.78947368, 4.88157895, 4.97368421,
       5.06578947, 5.15789474, 5.25      , 5.34210526, 5.43421053,
       5.52631579, 5.61842105, 5.71052632, 5.80263158, 5.89473684,
       5.98684211, 6.07894737, 6.17105263, 6.26315789, 6.35526316,
       6.44736842, 6.53947368, 6.63157895, 6.72368421, 6.81578

# 数组的属性

In [81]:
a = np.array(range(10))

In [74]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [75]:
#维度
a.ndim

1

In [79]:
#shape
a.shape

(9,)

In [82]:
#size
a.size

10

In [83]:
#dtype
a.dtype

dtype('int64')

In [84]:
#itmesize
a.itemsize

8

In [85]:
#nbytes
a.nbytes

80